/*
  DEMO ADMIN UI ONLY.
  DO NOT put a real admin password/secret in this file.
  Production: Firebase Auth + custom admin claim + Firestore Security Rules.
*/
const KEY="pm_demo_state_v2";
let S=JSON.parse(localStorage.getItem(KEY)||"null")||{matches:[],results:{},user:null};
const A="PM_DEMO_ADMIN_SESSION";
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function toast(x){const t=document.querySelector("#toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2000)}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function app(){if(sessionStorage.getItem(A)!=="1"){login();return}document.querySelector("#admin").innerHTML=`<header class="topbar"><div class="brand">PRIME <span>MIKU</span> ADMIN</div><button class="navbtn" onclick="logout()">Logout</button></header><main class="main"><div class="grid"><div class="card"><h2>Admin Dashboard</h2><p class="muted">Demo mode • production authorization must be server-side.</p><div class="stat">Matches: <b>${S.matches.length}</b></div><div class="stat" style="margin-top:8px">Players in current demo: <b>${S.user?1:0}</b></div></div><div class="card"><h2>Admin Online</h2><span class="online">ONLINE</span><p class="muted">Support status shown to players.</p></div></div><div class="section-title"><h2>Match Manager</h2><button class="btn" onclick="addMatch()">+ Add Match</button></div><div class="grid">${S.matches.map(matchAdmin).join("")||'<div class="card"><p>No matches yet.</p></div>'}</div><div class="section-title"><h2>Result Publisher</h2></div><div class="card">${resultForm()}</div></main>`}
function login(){document.querySelector("#admin").innerHTML=`<div class="auth-wrap"><div class="auth"><div class="auth-logo">PRIME <span>MIKU</span> ADMIN</div><div class="warning">🔒 Demo only. A production admin login must use Firebase Auth and an admin custom claim. Never publish an admin password in GitHub code.</div><form id="aform" class="form" style="margin-top:12px"><div class="field"><label>Demo admin ID</label><input required id="aid" value="admin"></div><div class="field"><label>Demo password</label><input required id="apass" type="password" value="demo"></div><button class="btn">Open Demo Panel</button></form></div></div>`;document.querySelector("#aform").onsubmit=e=>{e.preventDefault();sessionStorage.setItem(A,"1");app()}}
function logout(){sessionStorage.removeItem(A);login()}
function matchAdmin(m){return `<div class="card"><div class="match-top"><div><h3>${esc(m.title)}</h3><div class="muted">${new Date(m.start).toLocaleString()}</div></div><span class="badge">${m.players||0}/${m.max||50}</span></div><div class="match-meta"><div class="stat"><small>Status</small><b>${m.status}</b></div><div class="stat"><small>Access code</small><b>${m.accessCode||"—"}</b></div></div><div class="chips"><button class="btn secondary" onclick="editMatch('${m.id}')">Edit</button><button class="btn danger" onclick="deleteMatch('${m.id}')">Delete</button><button class="btn green" onclick="publishDemoResult('${m.id}')">Publish demo result</button></div></div>`}
function addMatch(){const title=prompt("Match title","Classic Bermuda #003");if(!title)return;const start=prompt("Start datetime ISO with timezone","2026-09-30T02:00:00+05:30");if(!start)return;const id="BM"+String(Date.now()).slice(-4);S.matches.push({id,title,start,players:0,max:50,fee:20,status:"upcoming",accessCode:Math.random().toString(36).slice(2,6).toUpperCase(),roomId:"ROOM-"+id,roomPass:Math.random().toString(36).slice(2,8).toUpperCase()});save();app()}
function editMatch(id){const m=S.matches.find(x=>x.id===id);if(!m)return;const start=prompt("New start ISO",m.start);if(start)m.start=start;const room=prompt("Room ID",m.roomId);if(room)m.roomId=room;const pass=prompt("Room password",m.roomPass);if(pass)m.roomPass=pass;save();app()}
function deleteMatch(id){if(!confirm("Delete this match from demo?"))return;S.matches=S.matches.filter(x=>x.id!==id);save();app()}
function publishDemoResult(id){const m=S.matches.find(x=>x.id===id);if(!m)return;const rows=[];if(S.user)rows.push({uid:S.user.id,name:S.user.gamingName||"Demo Player",level:"65",kills:Math.floor(Math.random()*10),reward:0});while(rows.length<5)rows.push({uid:"PMDEMO"+rows.length,name:"Player_"+(rows.length+1),level:String(50+rows.length),kills:Math.max(0,8-rows.length),reward:0});rows.sort((a,b)=>b.kills-a.kills);rows[0].reward=100;S.results[id]=rows;save();toast("Demo result published");app()}
function resultForm(){return `<p class="muted">Production admin will enter each joined player's UID, level and verified kills. The backend should validate admin authorization and write an immutable result/audit record.</p><button class="btn secondary" onclick="toast('Use Publish demo result for preview')">Result workflow</button>`}
Object.assign(window,{addMatch,editMatch,deleteMatch,publishDemoResult,logout});
document.addEventListener("DOMContentLoaded",app);
