import { firebaseConfig } from "./firebase-config.js";
// Firebase-ready imports. For a pure UI preview this app uses local demo storage.
// After adding firebase-config.js and enabling Auth/Firestore, replace the demo functions
// with Firebase Auth + Firestore calls described in README.md.
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getFirestore } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";

const hasConfig = firebaseConfig.apiKey && !firebaseConfig.apiKey.startsWith("YOUR_");
let fb = null;
if (hasConfig) {
  fb = initializeApp(firebaseConfig);
  getAuth(fb); getFirestore(fb);
}

const demoKey = "pm_demo_state_v2";
const uid = () => "PM"+Math.random().toString(36).slice(2,8).toUpperCase()+Math.floor(100+Math.random()*900);
const defaultState = {
  user:null, balance:100, joined:[], chats:[], withdrawals:[], paymentRequests:[],
  matches:[
    {id:"BM001",title:"Classic Bermuda #001",start:"2026-09-30T00:20:00+05:30",players:37,max:50,fee:20,status:"upcoming",accessCode:"7Q9K",roomId:"DEMO-ROOM-01",roomPass:"DEMO1234"},
    {id:"BM002",title:"Classic Bermuda #002",start:"2026-09-30T01:00:00+05:30",players:50,max:50,fee:20,status:"full",accessCode:"4M2P",roomId:"DEMO-ROOM-02",roomPass:"DEMO5678"}
  ],
  results:{}
};
let S=JSON.parse(localStorage.getItem(demoKey)||"null")||defaultState;
function save(){localStorage.setItem(demoKey,JSON.stringify(S))}
function toast(x){const t=document.querySelector("#toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function fmtTime(iso){return new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(iso))}
function countdown(iso){let d=Math.max(0,new Date(iso)-Date.now());let s=Math.floor(d/1000),h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);s%=60;return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
function isLocked(m){return new Date(m.start)-Date.now()<=10*60*1000}
function render(){document.querySelector("#app").innerHTML=S.user?shell():auth();setTimeout(tick,20)}
function auth(){
return `<div class="auth-wrap"><div class="auth"><div class="auth-logo">PRIME <span>MIKU</span></div>
<div class="tabs"><button id="tabLogin" class="active">Login</button><button id="tabReg">Register</button></div>
<div id="authForm"></div></div></div>`}
function authForm(mode="login"){const reg=mode==="reg";document.querySelector("#authForm").innerHTML=`<form class="form" id="authSubmit">
<div class="field"><label>Email</label><input required type="email" id="email" placeholder="player@email.com"></div>
<div class="field"><label>Password (exactly 4 characters)</label><input required minlength="4" maxlength="4" id="password" placeholder="1234" autocomplete="${reg?"new-password":"current-password"}"></div>
${reg?`<div class="warning">⚠️ Important: if you forget this 4-character password, account recovery is not available in this demo. For production, use Firebase Auth's normal recovery flow.</div>`:""}
<button class="btn">${reg?"Create Player Account":"Enter Arena"}</button>
</form>`;document.querySelector("#authSubmit").onsubmit=e=>{e.preventDefault();if(reg)register();else login()}}
function authSetup(){document.querySelector("#tabLogin").onclick=()=>{document.querySelector("#tabLogin").classList.add("active");document.querySelector("#tabReg").classList.remove("active");authForm("login")};document.querySelector("#tabReg").onclick=()=>{document.querySelector("#tabReg").classList.add("active");document.querySelector("#tabLogin").classList.remove("active");authForm("reg")};authForm()}
function register(){const email=document.querySelector("#email").value.trim(),password=document.querySelector("#password").value;if(password.length!==4)return toast("Password must be exactly 4 characters");S.user={id:uid(),email,password,gamingName:""};save();profileSetup()}
function login(){const email=document.querySelector("#email").value.trim(),password=document.querySelector("#password").value;if(!S.user||S.user.email!==email)return toast("Demo account not found — register first");if(password!==S.user.password)return toast("Wrong password");enterWelcome()}
function profileSetup(){document.querySelector("#app").innerHTML=`<div class="welcome"><div><div class="brand">PRIME <span>MIKU</span></div><h2>Choose your gaming name</h2><form id="nameForm" class="form" style="width:min(420px,90vw);margin:auto"><div class="field"><label>Gaming Name</label><input id="gname" required maxlength="18" placeholder="Your in-game name"></div><button class="btn">Enter The Arena</button></form></div></div>`;document.querySelector("#nameForm").onsubmit=e=>{e.preventDefault();S.user.gamingName=document.querySelector("#gname").value.trim();save();enterWelcome()}}
function enterWelcome(){document.querySelector("#app").innerHTML=`<div class="welcome"><div><div class="splash-logo">PRIME <span>MIKU</span></div><h1>WELCOME <span class="name">${esc(S.user.gamingName)}</span></h1><p class="muted">TO THE ARENA • FREE FIRE TOURNAMENT</p><button id="go" class="btn">Enter Arena</button></div></div>`;document.querySelector("#go").onclick=()=>{render();route("home")}}
function shell(){return `<div class="app"><header class="topbar"><div class="brand">PRIME <span>MIKU</span></div><div class="top-actions"><button class="navbtn hide-sm" onclick="route('wallet')">₹ ${S.balance.toFixed(0)}</button><button class="navbtn" onclick="logout()">Logout</button></div></header><div class="layout"><aside class="sidebar"><div class="side-user"><div class="avatar">${esc((S.user.gamingName||"P").slice(0,1).toUpperCase())}</div><b>${esc(S.user.gamingName)}</b><div class="uid">${S.user.id}</div></div><div class="side-links">${[['home','⌂ Home'],['matches','🎮 Classic Bermuda'],['results','🏆 Results'],['wallet','💳 Wallet'],['withdraw','💸 Withdraw'],['support','💬 Admin Support']].map(x=>`<button onclick="route('${x[0]}')">${x[1]}</button>`).join("")}</div></aside><main class="main" id="main"></main></div><div class="support"><button class="fab" onclick="route('support')">?</button></div></div>`}
function pageHome(){return `<div class="hero"><div class="hero-content"><div class="eyebrow">PRIME MIKU • FREE FIRE</div><h1>CLASSIC BERMUDA</h1><p>SOLO MATCH • 1 VS 49. Join an upcoming room and compete fairly.</p><div class="chips"><span class="chip">🎮 Solo</span><span class="chip">👥 50 Players</span><span class="chip">🔒 Room Lock: 10 min</span></div><div style="margin-top:15px"><button class="btn" onclick="route('matches')">VIEW MATCHES</button></div></div></div><div class="section-title"><h2>Live & Upcoming</h2><button class="navbtn" onclick="route('matches')">View all</button></div><div class="grid">${S.matches.slice(0,3).map(matchCard).join("")}</div>`}
function matchCard(m){const joined=S.joined.includes(m.id),locked=isLocked(m),full=m.players>=m.max;return `<div class="card match"><div class="match-top"><span class="badge ${m.status==='live'?'live':'up'}">${m.status==='live'?'● LIVE':'UPCOMING'}</span><span class="muted">${m.players}/${m.max}</span></div><h3>${esc(m.title)}</h3><div class="muted">${fmtTime(m.start)}</div><div class="match-meta"><div class="stat"><small>Entry</small><b>Demo ₹${m.fee}</b></div><div class="stat"><small>Starts in</small><b class="countdown" data-time="${m.start}">${countdown(m.start)}</b></div></div><button class="btn ${joined?'green':''}" ${full&&!joined?'disabled':''} onclick="openMatch('${m.id}')">${joined?'OPEN MATCH':full?'FULL':'JOIN MATCH'}</button>${locked&&!joined?'<div class="muted" style="margin-top:7px;font-size:11px">Room access is locked.</div>':''}</div>`}
function pageMatches(){return `<div class="section-title"><h2>Classic Bermuda</h2><span class="online">ADMIN ONLINE</span></div><div class="card"><p class="muted">Matches that finish are moved to history. In production this is done server-side with a scheduled backend job.</p></div><div class="grid">${S.matches.filter(m=>m.status!=="history").map(matchCard).join("")||'<div class="card"><h3>No open matches</h3></div>'}</div>`}
function pageResults(){let joined=S.joined.map(id=>S.matches.find(m=>m.id===id)).filter(Boolean);return `<div class="section-title"><h2>Match Results</h2></div>${joined.length?joined.map(m=>{let r=S.results[m.id];return `<div class="card" style="margin-bottom:12px"><div class="match-top"><div><b>${esc(m.title)}</b><div class="muted">${fmtTime(m.start)}</div></div><span class="badge">RESULTS</span></div>${r?resultTable(r):'<p class="muted">Admin has not published the result dashboard yet.</p>'}</div>`}).join(""):'<div class="card"><h3>No joined matches</h3><p class="muted">Join a Bermuda match to see its result dashboard here.</p></div>'}`}
function resultTable(r){let me=r.find(x=>x.uid===S.user.id);return `<div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>Player</th><th>UID</th><th>Level</th><th>Kills</th><th>Reward</th></tr></thead><tbody>${r.sort((a,b)=>b.kills-a.kills).map((x,i)=>`<tr><td class="rank">${i+1}</td><td>${esc(x.name)}</td><td>${esc(x.uid)}</td><td>${esc(x.level)}</td><td>${x.kills}</td><td>${x.reward?`₹${x.reward}`:'Try again next time'}</td></tr>`).join("")}</tbody></table></div>${me?`<div class="warning" style="margin-top:12px">${me.reward>0?`🤑 Your winning amount <b>₹${me.reward}</b> is ready to withdraw. Please input your UPI ID in the withdrawal section.`:'🎯 No kill recorded. Try again next time!'}</div>`:''}`}
function pageWallet(){return `<div class="section-title"><h2>Wallet</h2></div><div class="grid"><div class="card"><div class="muted">Available balance</div><div style="font:800 42px Orbitron;margin:10px 0">₹${S.balance.toFixed(2)}</div><button class="btn" onclick="demoAdd()">Add Balance (Demo)</button></div><div class="card"><h3>Payment verification</h3><p class="muted">Live UPI collection is intentionally not enabled in this GitHub demo. A production version needs a compliant payment provider/backend verification flow.</p><button class="btn secondary" onclick="toast('Production payment gateway goes here')">View payment instructions</button></div></div>`}
function pageWithdraw(){return `<div class="card"><h2>Withdraw</h2><p class="muted">For a production cash-prize system, withdrawal must be implemented through a compliant provider and server-side verification.</p><form id="wd" class="form"><div class="field"><label>UPI ID</label><input required id="upi" placeholder="name@upi"></div><div class="field"><label>Account / UPI Name</label><input required id="wname" placeholder="Name as shown in payment account"></div><div class="field"><label>Free Fire UID</label><input required id="wuid" value="${S.user.id}"></div><div class="field"><label>Amount</label><input required type="number" min="1" id="wamt" placeholder="Amount"></div><button class="btn">Submit withdrawal request</button></form></div>`}
function pageSupport(){return `<div class="card"><div class="match-top"><div><h2>Admin Support</h2><span class="online">Admin Online</span></div></div><div class="warning" style="margin:12px 0">⚠️ This is the main Admin. Please be respectful. Abusive behaviour may result in account suspension.</div><div class="chat" style="position:relative;right:auto;bottom:auto;width:100%;height:430px"><div class="chat-head"><b>Private support chat</b><span class="online">ONLINE</span></div><div class="messages" id="msgs">${S.chats.filter(x=>x.uid===S.user.id).map(x=>`<div class="msg ${x.from==='player'?'me':''}">${esc(x.text)}</div>`).join("")}</div><form id="chatForm" class="chat-form"><input id="chatText" placeholder="Describe your problem..." required><button class="btn">Send</button></form></div><div class="chips" style="margin-top:15px"><button class="navbtn" onclick="toast('YouTube link: configure in Admin Panel')">YouTube</button><button class="navbtn" onclick="toast('Instagram link: configure in Admin Panel')">Instagram</button><button class="navbtn" onclick="toast('Telegram link: configure in Admin Panel')">Telegram</button><button class="navbtn" onclick="toast('Facebook link: configure in Admin Panel')">Facebook</button></div></div>`}
function openMatch(id){const m=S.matches.find(x=>x.id===id);if(!m)return;if(S.joined.includes(id)){joinAccess(m);return}if(m.players>=m.max)return toast("Match is full");document.querySelector("#main").insertAdjacentHTML("beforeend",`<div class="modal-back" id="modal"><div class="modal"><h2>${esc(m.title)}</h2><p class="muted">Entry: Demo ₹${m.fee} • ${fmtTime(m.start)}</p><form id="joinForm" class="form"><div class="field"><label>Gaming UID</label><input required id="juid" placeholder="Your Free Fire UID"></div><div class="field"><label>Gaming Name</label><input required id="jname" value="${esc(S.user.gamingName)}"></div><div class="field"><label>Game Level</label><input required id="jlevel" placeholder="e.g. 65"></div><div class="rules"><b>Strict tournament rules</b><br>1. No hacks, scripts, injectors or modified clients.<br>2. No teaming or collusion in solo mode.<br>3. No abusive language or harassment.<br>4. Use the registered UID only.<br>5. Follow room ID/password instructions.<br>6. Admin decisions on verified rule violations are final for the event.<br>7. Do not share private room credentials publicly.</div><label><input required type="checkbox"> I agree to the tournament rules.</label><div class="match-meta"><div class="stat"><small>Wallet balance</small><b>₹${S.balance.toFixed(0)}</b></div><div class="stat"><small>Entry</small><b>Demo ₹${m.fee}</b></div></div><button class="btn">JOIN TOURNAMENT</button><button type="button" class="btn secondary" onclick="document.querySelector('#modal').remove()">Cancel</button></form></div></div>`);document.querySelector("#joinForm").onsubmit=e=>{e.preventDefault();if(S.balance<m.fee)return toast("Insufficient demo balance");S.balance-=m.fee;m.players++;S.joined.push(id);m.status=m.players>=m.max?"full":"upcoming";m.playerData={...(m.playerData||{}),[S.user.id]:{uid:document.querySelector("#juid").value,name:document.querySelector("#jname").value,level:document.querySelector("#jlevel").value,kills:0}};save();document.querySelector("#modal").remove();toast("Joined successfully");openMatch(id)}}
function joinAccess(m){const locked=isLocked(m);document.querySelector("#main").innerHTML=`<div class="card"><div class="match-top"><div><h2>${esc(m.title)}</h2><div class="muted">${fmtTime(m.start)}</div></div><span class="badge ${locked?'':'up'}">${locked?'ROOM LOCKED':'ROOM OPEN'}</span></div><div style="margin:18px 0"><div class="muted">Match starts in</div><div class="countdown" data-time="${m.start}">${countdown(m.start)}</div></div>${locked?`<div class="roomlock"><b>Room access code</b><p class="muted">Enter the personal code shown after locking. Only joined players should know their code.</p><input id="access" class="field input" maxlength="4" placeholder="XXXX"><button class="btn" style="margin-top:10px" onclick="revealRoom('${m.id}')">Unlock Room Details</button></div>`:`<div class="warning">Room ID & password will be shown 10 minutes before match start.</div>`}<button class="btn secondary" style="margin-top:12px" onclick="route('matches')">Back to Matches</button></div>`}
function revealRoom(id){const m=S.matches.find(x=>x.id===id);if(document.querySelector("#access").value.toUpperCase()!==m.accessCode)return toast("Invalid access code");document.querySelector("#main").innerHTML+=`<div class="modal-back" id="room"><div class="modal"><h2>🔓 Room Details</h2><div class="stat"><small>Room ID</small><b>${esc(m.roomId)}</b></div><div class="stat" style="margin-top:8px"><small>Password</small><b>${esc(m.roomPass)}</b></div><p class="warning" style="margin-top:12px">Do not share these credentials. Enter the room only at the announced time.</p><button class="btn" onclick="document.querySelector('#room').remove()">Done</button></div></div>`}
function pageProfile(){return `<div class="card"><h2>Player Profile</h2><div class="stat"><small>Player ID</small><b>${S.user.id}</b></div><div class="stat" style="margin-top:8px"><small>Gaming Name</small><b>${esc(S.user.gamingName)}</b></div><div class="stat" style="margin-top:8px"><small>Email</small><b>${esc(S.user.email)}</b></div></div>`}
function route(p){if(!S.user){render();authSetup();return}if(p==="profile")document.querySelector("#main").innerHTML=pageProfile();else if(p==="matches")document.querySelector("#main").innerHTML=pageMatches();else if(p==="results")document.querySelector("#main").innerHTML=pageResults();else if(p==="wallet")document.querySelector("#main").innerHTML=pageWallet();else if(p==="withdraw"){document.querySelector("#main").innerHTML=pageWithdraw();document.querySelector("#wd").onsubmit=e=>{e.preventDefault();toast("Withdrawal request saved in demo mode");}}else if(p==="support"){document.querySelector("#main").innerHTML=pageSupport();document.querySelector("#chatForm").onsubmit=e=>{e.preventDefault();S.chats.push({uid:S.user.id,from:"player",text:document.querySelector("#chatText").value});save();route("support")}}else document.querySelector("#main").innerHTML=pageHome();tick()}
function demoAdd(){S.balance+=20;save();toast("Demo balance +₹20");route("wallet")}
function logout(){S.user=null;save();render();authSetup()}
function tick(){document.querySelectorAll("[data-time]").forEach(e=>e.textContent=countdown(e.dataset.time));setTimeout(tick,1000)}
Object.assign(window,{route,openMatch,revealRoom,logout,demoAdd});
document.addEventListener("DOMContentLoaded",()=>{setTimeout(()=>{render();if(!S.user)authSetup();else route("home")},1500)})
